### A simple get request to the test endpoint. No need for login
GET {{url}}/auth/test/

### Create a new user - this one will only get a USER role by default
POST {{url}}/auth/register/

{
    "username": "test",
    "password": "test123"
}

###
POST {{url}}/auth/login/

{
    "username": "test",
    "password": "test123"
}

> {%
    client.global.set("jwt_token", response.body.token);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}

###
GET {{url}}/protected/user_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

###
GET {{url}}/protected/admin_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Add a new artist
POST {{url}}/api/artists
Content-Type: application/json

{
  "name": "Sire Bean",
  "type": "artist"
}

### Add album to artist (EXPERIMENTAL METHOD)
POST {{url}}/api/artists/1/add_album/0-1
Content-Type: application/json

{
  "name": "Sire Bean",
  "type": "artist"
}

### Retrieve all artists
GET {{url}}/api/artists

### Retrieve all albums
GET {{url}}/api/albums

### Retrieve all songs
GET {{url}}/api/songs

### Retrieve album by id
GET {{url}}/api/albums/1
Accept: application/json

### Add a new album
POST {{url}}/api/albums
Content-Type: application/json

{
  "name": "Gallicanae",
  "type": "album"
}

###
PUT {{url}}/api/albums/1
Content-Type: application/json

{
  "plantType": "Rose",
  "name": "Gallicanae",
  "maxHeight": 350,
  "price": 299.50
}

###
DELETE {{url}}/api/albums/1